spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    username : root
    format_sql: true
    use_sql_comments: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true   # put/delete httpMethod ??
